owner = "045978437674"
ami_elasticsearch = "ami-ubuntu-elasticsearch-*"
ami_logstash = "ami-ubuntu-logstash-*"
ami_kibana = "ami-ubuntu-kibana-*"
ami_filebeat = "ami-ubuntu-filebeat-*"
instance_type = "t3.large"